grasp_planning_server:
  ros__parameters:
    object_mesh_path: '/ros2_ws/src/wrs/pyhiro/suction/objects/sandpart2.stl'
    gripper_name: 'suction'
    contact:
      torque_resistance: 100
      min_distance: .1
      reduce_radius: 100