services:
    wros_humble_ws:
        build:
            context: "docker"
            dockerfile: "Dockerfile"
        container_name: wros_humble_container
        runtime: nvidia
        environment:
            - NVIDIA_VISIBLE_DEVICES=all
            - NVIDIA_DRIVER_CAPABILITIES=all
            - DISPLAY=$DISPLAY
            - QT_X11_NO_MITSHM=1
            - ROS_HOSTNAME=localhost
        volumes:
            - /dev:/dev
            - /tmp/.X11-unix:/tmp/.X11-unix:rw
            - ./ros2_ws/humble/src/wros2_tutorials:/ros2_ws/src/wros2_tutorials
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: 1
                          capabilities: [gpu]
        privileged: true
        tty: true
        network_mode: host
        command: bash -c "source /opt/ros/humble/setup.bash && colcon build --symlink-install --parallel-workers 1 && bash"
